import { getPages } from "@/sanity/lib/client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Projects Blog",
  description: "Generated by Next.js and Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className=" overflow-auto max-w-3xl mx-auto py-10 px-8 bg-slate-50 relative">
        <header className=" flex items-center justify-between mx-8">
          <Link
            href="/"
            className="font-serif font-bold rounded-full text-lg  bg-gradient-to-r from-purple-600 via-blue-600 to-orange-400"
          >
            &nbsp;&nbsp;&nbsp;&nbsp;ARB&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </Link>

          <div className="flex items-center text-sm gap-5 text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:bg-purple-500 hover:text-purple-100 transition bg-blue-100 rounded-lg text-gray-500 font-bold py-3 px-4 whitespace-nowrap"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className=" py-10 px-10">{children}</main>
      </body>
    </html>
  );
}
